#!/bin/sh
#
# Bootstrap script for setting up a new OSX machine
system_type=$(uname -s)

#
# This should be idempotent so it can be run multiple times.
#

if [ "$system_type" = "Darwin" ]; then

  # Because Git submodule commands cannot operate without a work tree, they must
  # be run from within $HOME (assuming this is the root of your dotfiles)
  cd "$HOME"

  echo "Init submodules"
  ~/.local/bin/yadm submodule update --recursive --init


  # requires xcode and tools!
  if ! command -v xcode-select -p &> /dev/null
  then
      echo "XCode must be installed! (run xcode-select --install)"
      xcode-select --install
  else
      echo "Xcode already installed"
  fi

  # homebrew
  if ! command -v /opt/homebrew/bin/brew &> /dev/null
  then
      echo 'brew must be installed! (/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)")'
  else
      echo "Homebrew already installed. Getting updates..."
      /opt/homebrew/bin/brew update
      /opt/homebrew/bin/brew doctor
  fi


  echo ">>> Installing brew packages.."
  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  # done
  echo "Bootstrapping complete"
fi
